# List of common vehicle manufacturer codes used in VIN and chassis numbers
# Format: prefix code -> manufacturer name

MANUFACTURER_CODES = {
    # Japanese Manufacturers
    'JF': 'Fuji Heavy Industries (Subaru)',
    'JH': 'Honda',
    'JM': 'Mazda',
    'JN': 'Nissan',
    'JS': 'Suzuki',
    'JT': 'Toyota',
    'JY': 'Yamaha',
    'MA': 'Mitsubishi',
    'MR': 'Mitsubishi',
    
    # European Manufacturers
    'SB': 'Saab',
    'SC': 'Saab',
    'VF': 'Peugeot/Citroën',
    'VR': 'Renault',
    'VS': 'Škoda',
    'VV': 'Volvo',
    'WA': 'Audi',
    'WB': 'BMW',
    'WD': 'Mercedes-Benz',
    'WDD': 'Mercedes-Benz',
    'WM': 'Opel',
    'WP': 'Porsche',
    'WV': 'Volkswagen',
    'YV': 'Volvo',
    'ZA': 'Autobianchi/Lancia',
    'ZF': 'Ferrari',
    
    # Additional European Manufacturers
    'SAH': 'McLaren',
    'WAU': 'Audi',
    'WBA': 'BMW',
    'WBS': 'BMW M',
    'WBY': 'BMW',
    'WF0': 'Ford (Germany)',
    'WME': 'Mercedes-Benz (Smart)',
    'WPO': 'Porsche',
    'WVGZ': 'Volkswagen',
    'WVWZ': 'Volkswagen',
    'XTA': 'Lada/AvtoVAZ',
    'ZFA': 'Fiat',
    'ZFF': 'Ferrari',
    
    # American Manufacturers
    '1G': 'General Motors',
    '1J': 'Jeep',
    '1M': 'Mercury',
    '1F': 'Ford',
    '1B': 'Dodge',
    '1C': 'Chrysler',
    '1D': 'Dodge',
    '2F': 'Ford (Canada)',
    '2G': 'General Motors (Canada)',
    '3F': 'Ford (Mexico)',
    '3G': 'General Motors (Mexico)',
    '3H': 'Honda (Mexico)',
    '3N': 'Nissan (Mexico)',
    '3V': 'Volkswagen (Mexico)',
    '4F': 'Mazda',
    '4M': 'Mercury',
    '4S': 'Subaru',
    '4T': 'Toyota',
    '5F': 'Honda',
    '5L': 'Lincoln',
    
    # Additional American Manufacturers
    '1GT': 'GMC',
    '1LN': 'Lincoln',
    '1ME': 'Mercury',
    '1N4': 'Nissan (USA)',
    '1N6': 'Nissan Truck (USA)',
    '1VW': 'Volkswagen (USA)',
    '2HG': 'Honda (Canada)',
    '2HK': 'Honda (Canada)',
    
    # Korean Manufacturers
    'KM': 'Hyundai',
    'KN': 'Kia',
    'KP': 'SsangYong',
    'KL': 'Daewoo',
    
    # Additional Asian Manufacturers
    'LC0': 'BYD Auto',
    'LFM': 'Changan Ford',
    'LFW': 'FAW Toyota',
    'LGB': 'BYD Auto',
    'LHG': 'Guangzhou Honda',
    'LJU': 'Beijing Hyundai',
    'LNB': 'Beijing Benz',
    'L6T': 'Chery',
    'MHL': 'Hyundai (India)',
    'MHR': 'Honda (India)',
    'MNT': 'Nissan (Thailand)',
    
    # Indian Manufacturers
    'MA3': 'Maruti Suzuki',
    'MAL': 'Mahindra & Mahindra',
    'MBH': 'Bajaj',
    'MBJ': 'Mahindra & Mahindra',
    'MC2': 'Volvo Eicher',
    'MCA': 'Fiat India',
    'MCB': 'General Motors India',
    'MCC': 'Tata Motors',
    
    # British Manufacturers
    'SA': 'Rover',
    'SAL': 'Land Rover',
    'SAR': 'Rover',
    'SAJ': 'Jaguar',
    'SAX': 'Austin/Rover',
    'SCA': 'Rolls-Royce',
    'SCC': 'Lotus',
    'SCF': 'Aston Martin',
    
    # Chinese Manufacturers
    'LBE': 'Beijing Jeep',
    'LBV': 'BMW Brilliance',
    'LDC': 'Dongfeng',
    'LFP': 'FAW',
    'LFV': 'FAW-Volkswagen',
    'LGB': 'Geely',
    'LGJ': 'Great Wall',
    'LJD': 'JAC',
    'LKL': 'Lifan',
    'LLV': 'Chery',
    'LSG': 'SAIC General Motors',
    'LSV': 'SAIC Volkswagen',
    'LTV': 'Toyota (China)',
    'LVS': 'Changan Suzuki',
    'LVV': 'Changan Volkswagen',
    'LZW': 'SAIC GM Wuling',
    
    # Other Manufacturers
    'AAV': 'Volkswagen (South Africa)',
    'AFA': 'Ford (South Africa)',
    'AHT': 'Toyota (South Africa)',
    'NMT': 'Toyota (Australia)',
    'TMT': 'Mitsubishi (Thailand)',
    'TRU': 'Isuzu (Thailand)',
    'MMB': 'Mitsubishi (Thailand)',
    'MPA': 'Isuzu (Thailand)',
    'MP1': 'Isuzu (Thailand)',
    'MNB': 'Ford (Thailand)',
    'TNZ': 'Toyota New Zealand',
    'VNK': 'Toyota (Brazil)',
    'VS6': 'Ford (Australia)',
    'WF0': 'Ford (Germany)',
    'ZFF': 'Ferrari',
    
    # Motorcycles
    'JH2': 'Honda',
    'JK': 'Kawasaki',
    'JY': 'Yamaha',
    'JS1': 'Suzuki',
    'VTT': 'Triumph',
    'ZDM': 'Ducati',
    
    # Additional Motorcycle Codes
    'KLE': 'Kawasaki',
    'ME1': 'Suzuki (India)',
    'MD2': 'Bajaj',
    'MMBZ': 'Hero MotoCorp',
    'RFBR': 'Yamaha (Indonesia)',
    'RKRB': 'Kawasaki (Indonesia)',
    'VTKA': 'KTM',
    'VTTM': 'Triumph',
    'WB10': 'BMW Motorcycles',
    
    # Heavy Vehicles
    'XLR': 'DAF Trucks',
    '1M1': 'Mack Trucks',
    '1M2': 'Mack Trucks',
    '2M': 'Mercury',
    '3H': 'Honda Mexico',
    'SUD': 'Scania',
    'YB1': 'Volvo Trucks',
    'YS2': 'Scania',
    'YS3': 'Saab',
    'YS4': 'Scania',
    'YV2': 'Volvo Trucks',
    'YV3': 'Volvo Buses',
    'YV4': 'Volvo',
    'WMA': 'MAN',
    'WMX': 'MAN',
    'VNE': 'Irisbus',
    'VLU': 'Scania',
    'WKEL': 'Kenworth Australia',
    'WKAH': 'Kenworth Australia',
    'WFOA': 'Ford Australia',
}